import Navigation from "@/components/Navigation";
import { useState } from 'react';
import { ChevronDown } from 'lucide-react';



interface Fact {
  id: number;
  category: string;
  fact: string;
  explanation: string;
}

const facts: Fact[] = [
  // Definition & Diagnosis (1-10)
  { id: 1, category: 'Definition & Diagnosis', fact: 'CPTSD is a mental health condition that develops following prolonged, repeated, or cumulative trauma, often involving interpersonal harm.', explanation: 'Complex Post-Traumatic Stress Disorder (CPTSD) is fundamentally different from single-event trauma. It develops when a person experiences multiple traumatic events over an extended period, such as childhood abuse lasting years, domestic violence in a long-term relationship, or repeated occupational trauma. The accumulation of these experiences creates a compound effect on the nervous system and psychological functioning.' },
  { id: 2, category: 'Definition & Diagnosis', fact: 'CPTSD was officially recognized in the ICD-11 (International Classification of Diseases, 11th Revision) by the World Health Organization in 2019.', explanation: 'The World Health Organization\'s International Classification of Diseases, 11th Revision (ICD-11) officially included CPTSD as a distinct diagnosis in 2019. This recognition validates decades of clinical observation and research showing that complex trauma produces a different symptom pattern than single-event PTSD. This official recognition has significant implications for treatment, insurance coverage, and research funding globally.' },
  { id: 3, category: 'Definition & Diagnosis', fact: 'CPTSD is distinct from PTSD, which typically results from a single traumatic event.', explanation: 'While PTSD develops from a single, time-limited traumatic event (such as a car accident, assault, or natural disaster), CPTSD develops from prolonged or repeated trauma. This distinction matters because it affects how symptoms present, how treatment approaches differ, and what recovery looks like. PTSD symptoms are typically more focused on re-experiencing the specific event, while CPTSD involves broader disturbances in self-organization.' },
  { id: 4, category: 'Definition & Diagnosis', fact: 'The global pooled prevalence of CPTSD is estimated at 6.2% in the general population.', explanation: 'Prevalence studies suggest that approximately 6.2% of the general population meets criteria for CPTSD. This means that roughly 1 in 16 people globally may have CPTSD. This statistic underscores the significant public health burden of complex trauma and highlights the need for increased awareness, training, and treatment resources.' },
  { id: 5, category: 'Definition & Diagnosis', fact: 'CPTSD prevalence is higher in trauma-exposed samples, reaching 12.4% globally.', explanation: 'Among people who have experienced trauma, the prevalence of CPTSD is approximately double that of the general population (12.4%). This makes sense because not all trauma exposure leads to CPTSD—factors like severity, duration, support systems, and individual resilience all influence whether someone develops the condition. This statistic shows that while trauma is common, CPTSD develops in a significant subset of trauma survivors.' },
  { id: 6, category: 'Definition & Diagnosis', fact: 'In the United States, approximately 3.8% of adults meet criteria for CPTSD.', explanation: 'U.S.-specific prevalence data shows that about 3.8% of American adults have CPTSD. This translates to millions of people in the United States alone. Despite this significant prevalence, CPTSD remains underdiagnosed and undertreated, partly because the DSM-5 (used in U.S. clinical practice) does not yet have a separate CPTSD diagnosis.' },
  { id: 7, category: 'Definition & Diagnosis', fact: 'CPTSD prevalence is highest in clinical populations at 44.7%.', explanation: 'Among people seeking mental health treatment, CPTSD prevalence is dramatically higher at 44.7%. This reflects the fact that untreated CPTSD causes significant functional impairment, leading people to seek professional help. This statistic highlights the importance of screening for complex trauma in clinical settings.' },
  { id: 8, category: 'Definition & Diagnosis', fact: 'Among domestic violence and sexual abuse survivors, CPTSD prevalence reaches 40%.', explanation: 'Survivors of domestic violence and sexual abuse have a 40% prevalence of CPTSD. These forms of interpersonal trauma are particularly damaging because they involve betrayal by someone in a position of trust or power. The chronic nature of domestic violence and the violation inherent in sexual abuse make these experiences particularly likely to produce CPTSD.' },
  { id: 9, category: 'Definition & Diagnosis', fact: 'CPTSD affects both children and adults, though it is more common in those with early trauma exposure.', explanation: 'While CPTSD can develop at any age following prolonged trauma, early childhood trauma exposure significantly increases the risk. Children who experience prolonged abuse, neglect, or exposure to violence during critical developmental periods are particularly vulnerable. Early trauma can affect brain development, attachment patterns, and emotional regulation in ways that have lifelong consequences.' },
  { id: 10, category: 'Definition & Diagnosis', fact: 'The DSM-5 does not yet have a separate diagnosis for CPTSD, though it is recognized in the ICD-11.', explanation: 'The Diagnostic and Statistical Manual of Mental Disorders, 5th Edition (DSM-5), used primarily in the United States, does not include a separate CPTSD diagnosis. Instead, complex trauma presentations are often diagnosed as PTSD with additional features or other diagnoses like Borderline Personality Disorder. This gap between the DSM-5 and ICD-11 has implications for diagnosis, treatment, and research in the U.S. mental health system.' },
  
  // Causes & Risk Factors (11-25)
  { id: 11, category: 'Causes & Risk Factors', fact: 'CPTSD typically results from prolonged child abuse, domestic violence, torture, or long-term captivity.', explanation: 'These are the prototypical causes of CPTSD. Prolonged child abuse creates a situation where the child cannot escape from the perpetrator and must develop survival strategies. Domestic violence similarly involves ongoing threat and control. Torture and captivity represent extreme forms of deliberate, prolonged harm. All of these share the common element of repeated, inescapable trauma.' },
  { id: 12, category: 'Causes & Risk Factors', fact: 'Repeated interpersonal trauma is the primary cause of CPTSD, distinguishing it from single-event PTSD.', explanation: 'The key distinguishing feature of CPTSD is that it results from interpersonal trauma—harm inflicted by other people—that is repeated over time. This is different from single-event PTSD, which can result from natural disasters, accidents, or other non-interpersonal events. The interpersonal nature of the trauma is crucial because it affects attachment, trust, and self-concept in particular ways.' },
  { id: 13, category: 'Causes & Risk Factors', fact: 'Childhood trauma is the most common precursor to CPTSD in adulthood.', explanation: 'Research consistently shows that adults with CPTSD typically have a history of childhood trauma. This makes sense because childhood is a critical period for developing emotional regulation, attachment, and sense of self. Trauma during this period can disrupt these fundamental developmental processes, creating vulnerabilities that persist into adulthood.' },
  { id: 14, category: 'Causes & Risk Factors', fact: 'Individuals with CPTSD report earlier age of trauma onset compared to those with PTSD alone.', explanation: 'On average, people with CPTSD experienced their first trauma at a younger age than those with PTSD alone. This early onset of trauma exposure is significant because it means the developing brain and personality are shaped by trauma, leading to more pervasive effects on self-concept and emotional regulation.' },
  { id: 15, category: 'Causes & Risk Factors', fact: 'Multiple trauma exposures significantly increase the risk of developing CPTSD.', explanation: 'The cumulative effect of multiple traumas is greater than the sum of individual traumas. Each additional trauma exposure increases the likelihood of developing CPTSD and typically increases symptom severity. This is why cumulative trauma burden is such an important concept in understanding CPTSD.' },
  { id: 16, category: 'Causes & Risk Factors', fact: 'Trauma occurring during critical developmental periods (childhood) increases CPTSD risk.', explanation: 'The brain undergoes critical developmental periods, particularly in childhood and adolescence. Trauma during these windows can disrupt normal brain development, particularly in areas responsible for emotional regulation, memory processing, and threat detection. This is why childhood trauma has such profound and lasting effects.' },
  { id: 17, category: 'Causes & Risk Factors', fact: 'Lack of escape or perceived inability to escape from trauma increases CPTSD likelihood.', explanation: 'A key factor in CPTSD development is the individual\'s sense that they cannot escape from the trauma. This might be literal (a child cannot leave home) or psychological (a person believes escape is impossible). This inescapability activates the nervous system\'s "freeze" response and prevents the normal resolution of the stress response cycle.' },
  { id: 18, category: 'Causes & Risk Factors', fact: 'Interpersonal betrayal by trusted caregivers is a significant risk factor for CPTSD.', explanation: 'When trauma is inflicted by someone who should provide safety and care—a parent, teacher, or trusted adult—the impact is particularly damaging. This betrayal violates the fundamental expectation of safety within a trusted relationship, creating deep wounds to attachment and trust that are central to CPTSD.' },
  { id: 19, category: 'Causes & Risk Factors', fact: 'Cumulative trauma burden—the total amount of trauma exposure—predicts CPTSD development.', explanation: 'Research shows that the total amount of trauma exposure (cumulative burden) is a strong predictor of CPTSD development. This is why someone who experienced one year of abuse might develop CPTSD while someone who experienced one traumatic event might develop PTSD instead. The cumulative effect matters more than any single incident.' },
  { id: 20, category: 'Causes & Risk Factors', fact: 'Individuals with CPTSD often experience trauma from multiple sources (e.g., family, community, institutional).', explanation: 'Many people with CPTSD have experienced trauma in multiple contexts—abuse at home, violence in the community, institutional abuse in schools or religious settings. This multi-source trauma creates a pervasive sense that danger exists everywhere and that no environment is truly safe.' },
  { id: 21, category: 'Causes & Risk Factors', fact: 'Prolonged institutional abuse (e.g., in orphanages, religious institutions) is a documented cause of CPTSD.', explanation: 'Institutional settings can become sites of prolonged abuse, particularly when there is little oversight or accountability. Children in orphanages, boarding schools, or religious institutions may experience systematic abuse over years. The institutional context makes escape impossible and often involves authority figures, compounding the trauma.' },
  { id: 22, category: 'Causes & Risk Factors', fact: 'Human trafficking and modern slavery are significant causes of CPTSD in vulnerable populations.', explanation: 'Human trafficking and modern slavery represent extreme forms of prolonged, repeated trauma involving captivity, violence, sexual abuse, and exploitation. Survivors of trafficking almost universally develop CPTSD due to the severity, duration, and multi-faceted nature of the trauma.' },
  { id: 23, category: 'Causes & Risk Factors', fact: 'Chronic medical trauma (repeated painful procedures, hospitalization) can contribute to CPTSD.', explanation: 'Individuals who experience repeated medical trauma—such as children with chronic illnesses requiring repeated painful procedures, or people with complex medical histories—can develop CPTSD. The medical setting, which should be safe, becomes associated with pain and threat.' },
  { id: 24, category: 'Causes & Risk Factors', fact: 'Occupational trauma (e.g., repeated exposure in first responders) can lead to CPTSD.', explanation: 'First responders (police, firefighters, paramedics), military personnel, and healthcare workers who experience repeated exposure to traumatic events can develop CPTSD. The cumulative exposure to others\' trauma, combined with the stress of the occupation, can lead to complex trauma responses.' },
  { id: 25, category: 'Causes & Risk Factors', fact: 'Intergenerational trauma may increase vulnerability to CPTSD in subsequent generations.', explanation: 'Children of parents with CPTSD may be at increased risk for developing CPTSD themselves. This can occur through parenting patterns (a parent with untreated CPTSD may struggle to provide safety and attunement), genetic predisposition to anxiety and stress sensitivity, or exposure to trauma-related family dynamics.' },
  
  // Core Symptoms (26-50)
  { id: 26, category: 'Core Symptoms', fact: 'Beyond PTSD symptoms, CPTSD includes disturbances in self-organization (DSO).', explanation: 'While CPTSD includes the core PTSD symptoms (re-experiencing, avoidance, hyperarousal), it also includes additional symptoms grouped under "disturbances in self-organization." These include affective dysregulation, negative self-concept, and relationship disturbances. These DSO symptoms are what make CPTSD distinct from PTSD.' },
  { id: 27, category: 'Core Symptoms', fact: 'Affective dysregulation—difficulty controlling emotions—is a hallmark of CPTSD.', explanation: 'Affective dysregulation means the nervous system has difficulty maintaining emotional equilibrium. People with CPTSD may swing rapidly between emotional states or have difficulty modulating emotional intensity. A minor trigger might provoke an intense anger or sadness response that feels disproportionate to the situation.' },
  { id: 28, category: 'Core Symptoms', fact: 'Individuals with CPTSD experience extreme emotional reactions to minor triggers.', explanation: 'Because the nervous system is sensitized by prolonged trauma, small reminders of trauma can trigger intense emotional responses. A tone of voice, a smell, or a particular situation might suddenly activate the trauma response, leading to overwhelming emotions that seem out of proportion to the current situation.' },
  { id: 29, category: 'Core Symptoms', fact: 'Persistent feelings of emptiness and despair are common in CPTSD.', explanation: 'Many people with CPTSD describe a pervasive sense of emptiness or hopelessness that exists even in the absence of acute trauma reminders. This reflects the deep impact of prolonged trauma on mood and motivation, and often requires treatment to address.' },
  { id: 30, category: 'Core Symptoms', fact: 'Negative self-concept is a core feature of CPTSD, including feelings of shame and guilt.', explanation: 'Prolonged interpersonal trauma, especially childhood abuse, creates a distorted self-image. Individuals with CPTSD often internalize blame for the trauma ("it was my fault"), develop shame about their trauma responses, and see themselves as fundamentally damaged or defective.' },
  { id: 31, category: 'Core Symptoms', fact: 'Many with CPTSD feel permanently damaged or fundamentally different from others.', explanation: 'This belief—that one is irreparably broken or fundamentally different from "normal" people—is a central feature of CPTSD. It reflects the deep impact of prolonged trauma on identity and self-worth. This belief often requires specific therapeutic work to address.' },
  { id: 32, category: 'Core Symptoms', fact: 'Disturbances in relationships are a defining feature of CPTSD.', explanation: 'Prolonged interpersonal trauma disrupts the ability to form and maintain healthy relationships. People with CPTSD may struggle with trust, have difficulty with emotional intimacy, or engage in patterns of relationship dysfunction that mirror their trauma.' },
  { id: 33, category: 'Core Symptoms', fact: 'Difficulty trusting others is extremely common in CPTSD due to interpersonal trauma.', explanation: 'When trauma is inflicted by people who should be trustworthy, the ability to trust is fundamentally damaged. People with CPTSD often struggle to believe that others have good intentions or that relationships can be safe. This makes forming new relationships and seeking help particularly challenging.' },
  { id: 34, category: 'Core Symptoms', fact: 'Individuals with CPTSD often isolate themselves from relationships.', explanation: 'As a protective mechanism, many people with CPTSD withdraw from relationships. Isolation feels safer than the risk of being hurt again. However, this isolation maintains CPTSD symptoms by preventing the corrective experience of safe relationships.' },
  { id: 35, category: 'Core Symptoms', fact: 'Flashbacks and intrusive memories are common in CPTSD, similar to PTSD.', explanation: 'Flashbacks—where traumatic memories feel like they\'re happening in the present—are a core symptom of both PTSD and CPTSD. In CPTSD, flashbacks often involve fragmented sensory memories rather than coherent narratives of the trauma.' },
  { id: 36, category: 'Core Symptoms', fact: 'Nightmares related to trauma are frequent in CPTSD.', explanation: 'Sleep disturbances, particularly trauma-related nightmares, are nearly universal in CPTSD. These nightmares can be terrifying and may prevent people from sleeping, leading to chronic sleep deprivation that worsens other symptoms.' },
  { id: 37, category: 'Core Symptoms', fact: 'Hypervigilance—constant scanning for danger—is prevalent in CPTSD.', explanation: 'The nervous system of someone with CPTSD remains in a state of high alert, constantly scanning for threats. This hypervigilance was adaptive during the trauma (it helped detect danger) but becomes maladaptive in safe environments, leading to exhaustion and difficulty relaxing.' },
  { id: 38, category: 'Core Symptoms', fact: 'Sleep disturbances are nearly universal in CPTSD.', explanation: 'Sleep problems in CPTSD are multifaceted—hyperarousal makes it hard to fall asleep, nightmares disrupt sleep, and the nervous system\'s heightened state prevents restorative sleep. Chronic sleep deprivation worsens all other CPTSD symptoms.' },
  { id: 39, category: 'Core Symptoms', fact: 'Dissociation (feeling disconnected from body or reality) is more common in CPTSD than PTSD.', explanation: 'Dissociation is a protective mechanism where the mind disconnects from overwhelming experiences. In CPTSD, dissociation is often more prominent than in PTSD, reflecting the more severe and prolonged nature of the trauma. Dissociation can range from mild (spacing out) to severe (dissociative identity disorder).' },
  { id: 40, category: 'Core Symptoms', fact: 'Depersonalization and derealization are frequent dissociative symptoms in CPTSD.', explanation: 'Depersonalization (feeling detached from your body) and derealization (feeling the world is unreal) are specific forms of dissociation common in CPTSD. These symptoms can be terrifying and contribute to a sense of unreality or disconnection from life.' },
  { id: 41, category: 'Core Symptoms', fact: 'Suicidal ideation is significantly higher in CPTSD compared to PTSD.', explanation: 'The combination of severe emotional pain, hopelessness, and negative self-concept in CPTSD leads to significantly higher rates of suicidal thinking. This makes CPTSD a serious mental health condition requiring prompt, specialized treatment.' },
  { id: 42, category: 'Core Symptoms', fact: 'Self-harm behaviors are more prevalent in CPTSD than in PTSD alone.', explanation: 'Self-harm (cutting, burning, or other self-injury) is a common coping mechanism in CPTSD. It may serve multiple functions—releasing emotional pressure, providing a sense of control, or creating physical pain that feels more manageable than emotional pain.' },
  { id: 43, category: 'Core Symptoms', fact: 'Substance abuse is a common coping mechanism in CPTSD.', explanation: 'Many people with CPTSD use substances (alcohol, drugs) to manage unbearable emotions, numb pain, or escape from trauma memories. While substances provide temporary relief, they ultimately worsen CPTSD symptoms and create additional problems.' },
  { id: 44, category: 'Core Symptoms', fact: 'Eating disorders are frequently comorbid with CPTSD.', explanation: 'Eating disorders often develop in people with CPTSD as a way to regain control, manage emotions, or punish the body. The control over eating can feel like the one thing a trauma survivor can control when so much else was taken from them.' },
  { id: 45, category: 'Core Symptoms', fact: 'Chronic pain is often associated with CPTSD.', explanation: 'Many people with CPTSD experience chronic pain without a clear medical cause. This "somatic pain" reflects the nervous system\'s state of hyperarousal and the way trauma is stored in the body. The pain is real, even though it doesn\'t have a clear physical cause.' },
  { id: 46, category: 'Core Symptoms', fact: 'Somatic symptoms (body-based complaints) are common in CPTSD.', explanation: 'Beyond pain, people with CPTSD often experience various physical symptoms—headaches, gastrointestinal issues, muscle tension, fatigue. These somatic symptoms reflect the mind-body connection and the way trauma affects the entire system.' },
  { id: 47, category: 'Core Symptoms', fact: 'Difficulty with emotional regulation can lead to explosive anger or complete emotional shutdown.', explanation: 'Affective dysregulation in CPTSD can manifest in two opposite ways—either explosive anger and emotional reactivity, or complete emotional numbness and shutdown. Some people alternate between these states, while others tend toward one pattern.' },
  { id: 48, category: 'Core Symptoms', fact: 'Individuals with CPTSD may experience prolonged grief reactions.', explanation: 'Grief in CPTSD is often complicated and prolonged. People may grieve the loss of a safe childhood, the loss of who they might have been without trauma, or losses related to the trauma itself. This grief can feel overwhelming and unresolvable.' },
  { id: 49, category: 'Core Symptoms', fact: 'Shame is often described as the most painful emotion in CPTSD.', explanation: 'While CPTSD involves many painful emotions, shame is often identified as the most damaging. Shame involves a sense of being fundamentally flawed or unworthy. Unlike guilt (which is about what you did), shame is about who you are. Addressing shame is a central goal of CPTSD treatment.' },
  { id: 50, category: 'Core Symptoms', fact: 'Depression is highly comorbid with CPTSD, affecting the majority of individuals.', explanation: 'Most people with CPTSD also experience depression. The persistent hopelessness, negative self-concept, and emotional pain of CPTSD create a fertile ground for depression. Treating both conditions simultaneously is often necessary.' },
  
  // Comorbidity (51-65)
  { id: 51, category: 'Comorbidity', fact: 'Anxiety disorders frequently co-occur with CPTSD.', explanation: 'The hyperarousal and hypervigilance of CPTSD create a state of chronic anxiety. Many people with CPTSD also meet criteria for specific anxiety disorders like generalized anxiety disorder or panic disorder.' },
  { id: 52, category: 'Comorbidity', fact: 'Borderline Personality Disorder (BPD) shares significant symptom overlap with CPTSD.', explanation: 'BPD and CPTSD share many symptoms, particularly emotional dysregulation and relationship difficulties. Some experts argue that many people diagnosed with BPD actually have CPTSD from early relational trauma. Distinguishing between these diagnoses is important for treatment planning.' },
  { id: 53, category: 'Comorbidity', fact: 'Attachment disorders are common in individuals who experienced early relational trauma.', explanation: 'Early relational trauma disrupts the formation of secure attachment. Children who experience abuse, neglect, or inconsistent caregiving may develop attachment disorders characterized by difficulty forming safe relationships.' },
  { id: 54, category: 'Comorbidity', fact: 'Chronic pain syndromes are frequently associated with CPTSD.', explanation: 'Conditions like fibromyalgia, chronic fatigue syndrome, and other pain syndromes are more common in people with CPTSD. The nervous system\'s dysregulation in CPTSD contributes to these pain conditions.' },
  { id: 55, category: 'Comorbidity', fact: 'Autoimmune disorders may be more prevalent in individuals with CPTSD.', explanation: 'Chronic stress and dysregulation of the immune system in CPTSD may increase vulnerability to autoimmune disorders. The mind-body connection means that prolonged psychological trauma can affect physical health.' },
  { id: 56, category: 'Comorbidity', fact: 'Substance Use Disorder is highly comorbid with CPTSD.', explanation: 'Many people with CPTSD develop substance use disorders as they attempt to self-medicate their symptoms. The high comorbidity of these conditions means that treatment often needs to address both simultaneously.' },
  { id: 57, category: 'Comorbidity', fact: 'Sleep disorders are nearly universal in CPTSD.', explanation: 'Beyond trauma-related nightmares, people with CPTSD often have difficulty with sleep architecture itself. The nervous system\'s dysregulation prevents the relaxation necessary for good sleep.' },
  { id: 58, category: 'Comorbidity', fact: 'Dissociative disorders are more common in CPTSD than in PTSD.', explanation: 'The more severe and prolonged nature of trauma in CPTSD leads to more prominent dissociative symptoms. Some people with severe CPTSD develop dissociative identity disorder (DID).' },
  { id: 59, category: 'Comorbidity', fact: 'Attention-Deficit/Hyperactivity Disorder (ADHD) symptoms may be exacerbated by CPTSD.', explanation: 'The hyperarousal and difficulty concentrating in CPTSD can mimic or exacerbate ADHD symptoms. Some people with CPTSD may be misdiagnosed as having ADHD when their symptoms are actually trauma-related.' },
  { id: 60, category: 'Comorbidity', fact: 'Obsessive-Compulsive Disorder (OCD) can co-occur with CPTSD.', explanation: 'Some people with CPTSD develop OCD-like symptoms as they attempt to manage anxiety through rituals and compulsions. The intrusive thoughts of CPTSD can become obsessive thoughts in OCD.' },
  { id: 61, category: 'Comorbidity', fact: 'Cardiovascular disease risk may be elevated in CPTSD due to chronic stress.', explanation: 'The chronic activation of the stress response system in CPTSD can lead to cardiovascular problems. Prolonged elevation of stress hormones and inflammation contribute to increased heart disease risk.' },
  { id: 62, category: 'Comorbidity', fact: 'Metabolic syndrome is more prevalent in individuals with CPTSD.', explanation: 'The chronic stress of CPTSD can contribute to metabolic dysfunction, including weight gain, insulin resistance, and dyslipidemia. The stress response system\'s dysregulation affects metabolism.' },
  { id: 63, category: 'Comorbidity', fact: 'Immune system dysfunction is documented in CPTSD.', explanation: 'Chronic stress in CPTSD leads to dysregulation of the immune system. This can manifest as increased susceptibility to infections or, conversely, as autoimmune activation.' },
  { id: 64, category: 'Comorbidity', fact: 'Chronic inflammation markers are elevated in individuals with CPTSD.', explanation: 'Research shows that people with CPTSD have elevated inflammatory markers in their blood. This systemic inflammation contributes to various health problems and may accelerate aging.' },
  { id: 65, category: 'Comorbidity', fact: 'CPTSD significantly impairs occupational functioning and employment stability.', explanation: 'The symptoms of CPTSD—difficulty concentrating, emotional dysregulation, hypervigilance—make it challenging to maintain employment. Many people with untreated CPTSD experience frequent job loss and employment instability.' },
  
  // Daily Life Impact (66-75)
  { id: 66, category: 'Daily Life Impact', fact: 'Educational attainment is often lower in individuals with untreated CPTSD.', explanation: 'CPTSD symptoms interfere with learning and academic performance. Difficulty concentrating, emotional dysregulation, and the need to manage trauma symptoms make it harder to complete education.' },
  { id: 67, category: 'Daily Life Impact', fact: 'Social relationships are severely affected by CPTSD symptoms.', explanation: 'The difficulty with trust, emotional dysregulation, and relationship patterns in CPTSD make it challenging to form and maintain healthy friendships and romantic relationships.' },
  { id: 68, category: 'Daily Life Impact', fact: 'Parenting capacity may be compromised in individuals with active CPTSD.', explanation: 'Parents with untreated CPTSD may struggle to provide emotional attunement, consistent boundaries, or safety for their children. This can perpetuate intergenerational trauma if not addressed.' },
  { id: 69, category: 'Daily Life Impact', fact: 'Financial instability is more common in individuals with CPTSD.', explanation: 'Employment difficulties, impulsive spending (sometimes related to emotional dysregulation), and the costs of managing symptoms lead to financial instability in many people with CPTSD.' },
  { id: 70, category: 'Daily Life Impact', fact: 'Housing instability and homelessness are overrepresented in CPTSD populations.', explanation: 'The combination of employment difficulties, relationship problems, and untreated symptoms can lead to housing instability. People with CPTSD are overrepresented among homeless populations.' },
  { id: 71, category: 'Daily Life Impact', fact: 'Quality of life is substantially reduced in CPTSD compared to the general population.', explanation: 'Overall life satisfaction, sense of meaning, and enjoyment of activities are significantly diminished in CPTSD. This reflects the pervasive impact of trauma on all life domains.' },
  { id: 72, category: 'Daily Life Impact', fact: 'Individuals with CPTSD have higher healthcare utilization rates.', explanation: 'People with CPTSD use healthcare services more frequently due to both mental health symptoms and physical health problems associated with chronic stress.' },
  { id: 73, category: 'Daily Life Impact', fact: 'Medical costs associated with CPTSD are substantial due to comorbid conditions.', explanation: 'The direct and indirect costs of CPTSD—including treatment, lost productivity, and health complications—are substantial. This represents a significant public health burden.' },
  { id: 74, category: 'Daily Life Impact', fact: 'CPTSD can lead to social withdrawal and isolation, worsening symptoms.', explanation: 'As a protective mechanism, people with CPTSD often withdraw from social contact. However, this isolation prevents the corrective experience of safe relationships and worsens symptoms over time.' },
  { id: 75, category: 'Daily Life Impact', fact: 'Treatment duration for CPTSD typically ranges from 3-4 months for trauma-focused therapy.', explanation: 'While some people benefit from shorter treatment, many people with CPTSD require longer-term therapy. The 3-4 month timeframe refers to intensive trauma-focused therapy, but ongoing support may be beneficial.' },
  
  // Treatment & Recovery (76-100)
  { id: 76, category: 'Treatment & Recovery', fact: 'Trauma-focused cognitive behavioral therapy (TF-CBT) is evidence-based for CPTSD.', explanation: 'TF-CBT is one of the most researched and effective treatments for CPTSD. It combines cognitive-behavioral techniques with direct processing of trauma memories. TF-CBT typically involves 12-16 sessions.' },
  { id: 77, category: 'Treatment & Recovery', fact: 'Cognitive Processing Therapy (CPT) has strong evidence for treating CPTSD.', explanation: 'CPT focuses on processing the trauma through examining and challenging trauma-related thoughts. It has strong evidence for CPTSD and typically involves 12 sessions.' },
  { id: 78, category: 'Treatment & Recovery', fact: 'Prolonged Exposure (PE) therapy is effective for CPTSD.', explanation: 'PE involves gradually confronting trauma-related memories and situations. While it can be challenging, PE has strong evidence for treating CPTSD and typically requires 8-15 sessions.' },
  { id: 79, category: 'Treatment & Recovery', fact: 'Eye Movement Desensitization and Reprocessing (EMDR) is an evidence-based treatment for CPTSD.', explanation: 'EMDR uses bilateral stimulation (eye movements, tapping, or sounds) to help process traumatic memories. It has strong evidence for CPTSD and appeals to many because it doesn\'t require detailed verbal processing of trauma.' },
  { id: 80, category: 'Treatment & Recovery', fact: 'Phase-based treatment approaches (e.g., STAIR) may be beneficial for CPTSD.', explanation: 'Phase-based approaches recognize that people with severe CPTSD may need stabilization before directly processing trauma. These approaches typically involve three phases: stabilization, trauma processing, and integration.' },
  { id: 81, category: 'Treatment & Recovery', fact: 'Stabilization and skill-building are often necessary before trauma processing in CPTSD.', explanation: 'Many people with CPTSD are too dysregulated to safely process trauma directly. Building emotional regulation skills, developing safety plans, and establishing stability first makes trauma processing more effective.' },
  { id: 82, category: 'Treatment & Recovery', fact: 'Psychopharmacology (medication) can help manage CPTSD symptoms, though it is not a cure.', explanation: 'Medications like SSRIs can help manage depression, anxiety, and other CPTSD symptoms. However, medication alone is not sufficient—psychotherapy is essential for addressing the core trauma.' },
  { id: 83, category: 'Treatment & Recovery', fact: 'SSRIs (Selective Serotonin Reuptake Inhibitors) are commonly prescribed for CPTSD.', explanation: 'SSRIs are the first-line medication for CPTSD, helping with depression and anxiety. Common SSRIs include sertraline, paroxetine, and fluoxetine.' },
  { id: 84, category: 'Treatment & Recovery', fact: 'Trauma-informed yoga and mindfulness may support CPTSD recovery.', explanation: 'Trauma-informed yoga and mindfulness practices help people reconnect with their bodies and develop emotional regulation skills. These should complement, not replace, evidence-based trauma therapy.' },
  { id: 85, category: 'Treatment & Recovery', fact: 'Group therapy can be beneficial for CPTSD, providing community and validation.', explanation: 'Group therapy allows people with CPTSD to connect with others who understand their experience. The sense of community and reduced isolation can be powerful healing factors.' },
  { id: 86, category: 'Treatment & Recovery', fact: 'Peer support groups are valuable resources for individuals with CPTSD.', explanation: 'Support groups (both in-person and online) provide practical strategies, emotional support, and a sense of belonging. Many people find peer support as valuable as professional treatment.' },
  { id: 87, category: 'Treatment & Recovery', fact: 'Recovery from CPTSD is possible with appropriate treatment and support.', explanation: 'While CPTSD cannot be "cured" in the traditional sense, recovery is absolutely possible. Many people with CPTSD achieve significant symptom reduction and move from survival to thriving.' },
  { id: 88, category: 'Treatment & Recovery', fact: 'Long-term outcomes show that active treatment yields large symptom reductions lasting at least 12 months.', explanation: 'Research demonstrates that people who engage in evidence-based treatment for CPTSD show substantial and lasting improvement. The benefits of treatment persist long-term.' },
  { id: 89, category: 'Treatment & Recovery', fact: 'Relapse prevention is an important component of CPTSD treatment.', explanation: 'As part of treatment, people learn strategies for managing difficult periods and preventing relapse. Having a plan for managing setbacks helps maintain progress.' },
  { id: 90, category: 'Treatment & Recovery', fact: 'With treatment, many individuals with CPTSD achieve significant symptom reduction.', explanation: 'The majority of people who engage in evidence-based treatment for CPTSD experience meaningful improvement in symptoms and functioning.' },
  { id: 91, category: 'Treatment & Recovery', fact: 'Resilience factors (social support, coping skills, sense of purpose) predict better CPTSD outcomes.', explanation: 'People with strong support systems, effective coping strategies, and a sense of meaning or purpose tend to have better treatment outcomes. These factors can be developed and strengthened.' },
  { id: 92, category: 'Treatment & Recovery', fact: 'Trauma-informed care approaches improve treatment engagement and outcomes in CPTSD.', explanation: 'When treatment is delivered in a trauma-informed manner—with attention to safety, trustworthiness, and collaboration—people are more likely to engage and benefit.' },
  { id: 93, category: 'Treatment & Recovery', fact: 'Self-compassion and acceptance are important components of CPTSD recovery.', explanation: 'Learning to treat oneself with kindness rather than harsh judgment is crucial for CPTSD recovery. Acceptance of what happened (without condoning it) is also important for moving forward.' },
  { id: 94, category: 'Treatment & Recovery', fact: 'Building healthy relationships is a key aspect of CPTSD recovery.', explanation: 'Safe, supportive relationships are healing. As people recover from CPTSD, they often develop deeper capacity for connection and intimacy.' },
  { id: 95, category: 'Treatment & Recovery', fact: 'Developing a sense of purpose or meaning supports CPTSD recovery.', explanation: 'Finding meaning in one\'s experience—whether through helping others, creative expression, or spiritual practice—supports healing and prevents relapse.' },
  { id: 96, category: 'Treatment & Recovery', fact: 'Addressing shame is a central goal of CPTSD treatment.', explanation: 'Shame is often the most painful and persistent symptom of CPTSD. Specific therapeutic techniques help people move from shame to self-compassion.' },
  { id: 97, category: 'Treatment & Recovery', fact: 'Recovery from CPTSD is not linear; setbacks are normal and expected.', explanation: 'Healing from CPTSD is a process with ups and downs. Setbacks don\'t mean failure—they\'re a normal part of recovery. Having realistic expectations helps people persist through difficult periods.' },
  { id: 98, category: 'Treatment & Recovery', fact: 'Post-traumatic growth—positive change resulting from trauma recovery—is possible.', explanation: 'Many people who recover from CPTSD report positive changes including increased empathy, deeper relationships, greater appreciation for life, and personal strength. These represent genuine growth, not just symptom reduction.' },
  { id: 99, category: 'Treatment & Recovery', fact: 'You are not alone in CPTSD; millions of people worldwide are on a recovery journey.', explanation: 'CPTSD affects millions of people globally. You are not alone in your experience. Recovery is possible, support is available, and many people have successfully healed from CPTSD.' },
  { id: 100, category: 'Treatment & Recovery', fact: 'CPTSD is a treatable condition; seeking help is a sign of strength, not weakness.', explanation: 'While CPTSD is serious and complex, it is highly treatable with the right support. Reaching out for help—whether from a therapist, support group, or trusted person—is an act of courage and self-compassion.' },
];

function FactAccordion() {
  const [expandedId, setExpandedId] = useState<number | null>(null);

  const categories = Array.from(new Set(facts.map(item => item.category)));

  return (
    <div className="space-y-8">
      {categories.map(category => (
        <div key={category}>
          <h3 className="text-2xl font-bold mb-4 text-primary">{category}</h3>
          <div className="space-y-3">
            {facts
              .filter(item => item.category === category)
              .map(item => (
                <div
                  key={item.id}
                  className="border border-border rounded-lg overflow-hidden bg-card hover:shadow-md transition-shadow"
                >
                  <button
                    onClick={() => setExpandedId(expandedId === item.id ? null : item.id)}
                    className="w-full px-6 py-4 flex items-start justify-between text-left hover:bg-muted/50 transition-colors gap-4"
                  >
                    <div className="flex-1">
                      <span className="font-semibold text-card-foreground text-sm md:text-base">{item.id}. {item.fact}</span>
                    </div>
                    <ChevronDown
                      className={`flex-shrink-0 w-5 h-5 text-primary transition-transform mt-1 ${
                        expandedId === item.id ? 'rotate-180' : ''
                      }`}
                    />
                  </button>
                  {expandedId === item.id && (
                    <div className="px-6 py-4 bg-muted/30 border-t border-border text-card-foreground text-sm leading-relaxed">
                      <p className="font-semibold mb-2">Why This Matters:</p>
                      {item.explanation}
                    </div>
                  )}
                </div>
              ))}
          </div>
        </div>
      ))}
    </div>
  );
}

export default function Facts() {
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
 <Navigation />

      {/* Main Content */}
      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-gradient-to-b from-primary/10 to-background py-12 md:py-20">
          <div className="container">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">100 Facts About CPTSD</h2>
            <p className="text-lg text-muted-foreground max-w-2xl">
              Click on any fact to learn more about why it matters and how it relates to Complex Post-Traumatic Stress Disorder.
            </p>
          </div>
        </section>

        {/* Facts Content */}
        <section className="py-12 md:py-16">
          <div className="container max-w-4xl">
            <FactAccordion />
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-muted border-t border-border mt-12">
        <div className="container py-8">
          <p className="text-sm text-muted-foreground">
            © 2025 CPTSD Educational Resource. These facts are based on research and clinical evidence. For personalized advice, consult with a mental health professional.
          </p>
        </div>
      </footer>
    </div>
  );
}
